config/routes.rb
Rails.application.routes.draw do
    resources :produtos
    resources :pedidos
    resources :enderecos
    resources :clientes
  # root to: "home#index"
    devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
    root "home#index"
    # root "devise/sessions#new"
    #root :to => "devise/sessions#new"

    get '/users', to: 'users#index'
end

app/models/pedido.rb
class Pedido < ApplicationRecord
    validates :codigo, presence: { message: "do pedido deve ser preenchido" }
    validates :codigo, uniqueness: { message: "do pedido já existe" }
    validates :codigo, length: { is: 4, message: "do pedido deve conter 4 dígitos" }
    validates :codigo, numericality: { only_integer: true, message: "do pedido deve conter apenas números" }

    belongs_to :cliente
    has_and_belongs_to_many :produtos
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]

  # GET /pedidos or /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos or /pedidos.json
  def create
    # pedido_params[:produto_ids].reject!(&:blank?)
    @pedido = Pedido.new
    @pedido.codigo = pedido_params[:codigo]
    @pedido.cliente = Cliente.find_by(cpf: pedido_params[:cliente_id])

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
        return
      end
    end

    pedido_params[:produto_ids].each do |produto_id|
        produto = Produto.find_by(id: produto_id)
        if produto != nil
            @pedido.produtos << produto
        end
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    @pedido.destroy

    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: "Pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:codigo, :cliente_id, :produto_ids => [])
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido) do |form| %>
    <% if pedido.errors.any? %>
        <div style="color: red">
        <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

        <ul>
            <% pedido.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

        <div>
            <%= form.label "Código", style: "display: block" %>
            <%= form.text_field :codigo %>
        </div>

        <div>
            <%= form.label :cliente_id, style: "display: block" %>
            <%= form.text_field :cliente_id %>
        </div>

        <div>
            <%= form.label :produtos, style: "display: block" %>
            <!-- <%= collection_check_boxes(:pedido, :produto_ids, Produto.all, :id, :nome) %> -->
            <%= form.collection_check_boxes :produto_ids, Produto.where.not(id: nil).order(:nome), :id, :nome do |b| %>
                <div class="collection-check-box">
                    <%= b.check_box %>
                    <%= b.label %>
                </div>
            <% end %>
        </div>

        <br>
            <%= form.submit "Salvar pedido", class: "button" %>
    <% end %>

app/views/pedidos/_pedido.html.erb
<div id="<%= dom_id pedido %>" class="item">
    <p>
        <strong>Código:</strong>
        <%= pedido.codigo %>
    </p>

    <p>
        <strong>Cliente:</strong>
        <%= pedido.cliente.cpf %>
    </p>

     <p>
        <strong>Produtos:</strong>
        <%= pedido.produtos.map(&:nome).join(", ") %>
    </p>
</div>

app/views/pedidos/edit.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

<body>
    <main>
        <h1>Editando pedido</h1>
        <%= render "form", pedido: @pedido %>
        <br>

        <p>
            <!-- <%= link_to "Exibir esse pedido", @pedido %> | -->
            <%= link_to "Voltar para pedidos", pedidos_path %>
        </p>
    </main>
</body>

app/views/pedidos/index.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

<main>
    <body>
        <h1>Pedidos</h1>
        <br>
        <div id="pedidos">
            <% @pedidos.each do |pedido| %>
                <p><b>Código:</b> <%= pedido.codigo %><br>
                <%= link_to "Exibir pedido", pedido %></p>
                <br>
            <% end %>
        </div>
        <p><%= link_to "Voltar para início", root_path %>
        <% if current_user.admin? %>
            | <%= link_to "Novo pedido", new_pedido_path %></p>
        <% end %>
    </body>
</main>

app/views/pedidos/new.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

<body>    
    <main>
        <h1>Novo pedido</h1>
        <%= render "form", pedido: @pedido %>
        <br>

        <p><%= link_to "Voltar para pedidos", pedidos_path %></p>
    </main>
</body>

app/views/pedidos/show.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

<body>
    <main>
        <p style="color: green"><%= notice %></p>
        <%= render @pedido %>
        <p>
            <%= link_to "Voltar para pedidos", pedidos_path %>
            <% if current_user.admin? %>
                | <%= link_to "Editar pedido", edit_pedido_path(@pedido) %>
            <% end %>
        </p>
         <% if current_user.admin? %>
            <p><div class="delete_button"><%= button_to "Excluir pedido", @pedido, method: :delete, form_class: "button", data: { confirm: 'Você tem certeza que deseja deletar essa entrada?' } %></div></p>
        <% end %>
    </main>
</body>