config/routes.rb
Rails.application.routes.draw do
    resources :produtos
    resources :pedidos
    resources :enderecos
    resources :clientes
  # root to: "home#index"
    devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
    root "home#index"
    # root "devise/sessions#new"
    #root :to => "devise/sessions#new"

    get '/users', to: 'users#index'
end

app/models/pedido.rb
class Pedido < ApplicationRecord
    validates :codigo, presence: { message: "do pedido deve ser preenchido" }
    validates :codigo, uniqueness: { message: "do pedido já existe" }
    validates :codigo, length: { is: 4, message: "do pedido deve conter 4 dígitos" }
    validates :codigo, numericality: { only_integer: true, message: "do pedido deve conter apenas números" }

    belongs_to :cliente
    has_and_belongs_to_many :produtos
end

app/models/produto.rb
class Produto < ApplicationRecord
    validates :nome, :preco, presence: { message: "deve ser preenchido" }
    validates :estoque, numericality: { only_integer: true, message: "deve conter apenas números" }
    validates :nome, uniqueness: { message: "já existe" }
    validates :preco, numericality: { only_numeric: true, message: "do pedido deve conter apenas números" }
    # validates :preco, format: { with: /\A[0-9.]+\z/, message: "deve conter apenas números" }

    has_and_belongs_to_many :pedidos
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
    before_action :set_produto, only: %i[ show edit update destroy ]

    # GET /produtos or /produtos.json
    def index
        @produtos = Produto.all
    end

    # GET /produtos/1 or /produtos/1.json
    def show
    end

    # GET /produtos/new
    def new
        @produto = Produto.new
    end

    # GET /produtos/1/edit
    def edit
    end

    # POST /produtos or /produtos.json
    def create
        @produto = Produto.new(produto_params)

        respond_to do |format|
        if @produto.save
            format.html { redirect_to produto_url(@produto), notice: "Produto was successfully created." }
            format.json { render :show, status: :created, location: @produto }
        else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @produto.errors, status: :unprocessable_entity }
        end
        end
    end

    # PATCH/PUT /produtos/1 or /produtos/1.json
    def update
        respond_to do |format|
            if @produto.update(produto_params)
                format.html { redirect_to produto_url(@produto), notice: "Produto was successfully updated." }
                format.json { render :show, status: :ok, location: @produto }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @produto.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /produtos/1 or /produtos/1.json
    def destroy
        @produto.destroy

        respond_to do |format|
        format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
        format.json { head :no_content }
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
    def set_produto
        @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
        params.require(:produto).permit(:nome, :preco, :estoque, :pedido_ids => [])
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :preco, style: "display: block" %>
    <%= form.text_field :preco %>
  </div>

  <div>
    <%= form.label :estoque, style: "display: block" %>
    <%= form.number_field :estoque %>
  </div>

    <div>
        <%= form.label :pedidos, style: "display: block" %>
        <!-- <%= collection_check_boxes(:pedido, :produto_ids, Produto.all, :id, :nome) %> -->
        <%= form.collection_check_boxes :pedido_ids, Pedido.where.not(id: nil).order(:codigo), :id, :codigo do |b| %>
            <div class="collection-check-box">
                <%= b.check_box %>
                <%= b.label %>
            </div>
      <% end %>
    </div>

     <br>
    <%= form.submit "Salvar pedido", class: "button" %>
<% end %>

app/views/produtos/_produto.html.erb
<div id="<%= dom_id produto %>" class="item">
    <p>
        <strong>Nome:</strong>
        <%= produto.nome %>
    </p>

    <p>
        <strong>Preço:</strong>
        <%= produto.preco %>
    </p>

    <p>
        <strong>Estoque:</strong>
        <%= produto.estoque %>
    </p>

    <p>
        <strong>Pedidos:</strong>
        <%= produto.pedidos.map(&:codigo).join(", ") %>
    </p>
</div>

app/views/produtos/edit.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

<body>
    <main>
        <h1>Editando produto</h1>
        <%= render "form", produto: @produto %>
        <br>

        <p>
            <!-- <%= link_to "Exibir esse produto", @produto %> | -->
            <%= link_to "Voltar para produtos", produtos_path %>
        </p>
    </main>
</body>

app/views/produtos/index.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

<main>
    <body>
        <h1>Produtos</h1>
        <br>
        <div id="produtos">
            <% @produtos.each do |produto| %>
                <p><b>Nome:</b> <%= produto.nome %><br>
                <%= link_to "Exibir produto", produto %></p>
                <br>
            <% end %>
        </div>
        <p><%= link_to "Voltar para início", root_path %>
        <% if current_user.admin? %>
        | <%= link_to "Novo produto", new_produto_path %>
        <% end %></p>
    </body>
</main>

app/views/produtos/new.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

<body>    
    <main>
        <h1>Novo produto</h1>
        <%= render "form", produto: @produto %>
        <br>

        <p><%= link_to "Voltar para produtos", produtos_path %></p>
    </main>
</body>

app/views/produtos/show.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">

<body>
    <main>
        <p style="color: green"><%= notice %></p>
        <%= render @produto %>
        <p>
            <%= link_to "Voltar para produtos", produtos_path %>
            <% if current_user.admin? %>
            | <%= link_to "Editar produto", edit_produto_path(@produto) %>
            <% end %>
        </p>
        <% if current_user.admin? %>
            <p><div class="delete_button"><%= button_to "Excluir produto", @produto, method: :delete, form_class: "button",  data: { confirm: 'Você tem certeza que deseja deletar essa entrada?' } %></div></p>
        <% end %>
    </main>
</body>